# **Data Cleaning and Preparation for Ensuring Data Integrity**

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Step 1: Import Libraries

In [4]:
import pandas as pd
import numpy as np

# Step 2: Upload Dataset

In [5]:
from google.colab import files

uploaded = files.upload()

Saving Dataset for Data Analytics.xlsx to Dataset for Data Analytics (1).xlsx

# Step 3: Read Excel File

In [6]:
df = pd.read_excel("Dataset for Data Analytics.xlsx")

df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

# Step 4: Check Dataset Information

In [7]:
print(df.shape)

(1200, 14)

In [8]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   datetime64[ns]
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(9)
memory usage: 131.4+ KB
None

In [9]:
df.describe()

                      Date     Quantity    UnitPrice  ItemsInCart   TotalPrice
count                 1200  1200.000000  1200.000000  1200.000000  1200.000000
mean   2024-03-22 16:58:48     2.945833   356.412750     5.485000  1053.968300
min    2023-01-01 00:00:00     1.000000    11.390000     1.000000    11.390000
25%    2023-08-03 18:00:00     2.000000   186.062500     4.000000   410.520000
50%    2024-03-23 00:00:00     3.000000   364.210000     5.000000   823.615000
75%    2024-11-08 12:00:00     4.000000   521.570000     7.000000  1578.475000
max    2025-06-30 00:00:00     5.000000   699.930000    10.000000  3456.400000
std                    NaN     1.407557   197.177146     2.281983   819.856558

# Step 5: Find Missing Values

In [10]:
df.isnull().sum()

OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

In [11]:
missing=(df.isnull().sum()/len(df))*100

print(missing)

OrderID             0.00
Date                0.00
CustomerID          0.00
Product             0.00
Quantity            0.00
UnitPrice           0.00
ShippingAddress     0.00
PaymentMethod       0.00
OrderStatus         0.00
TrackingNumber      0.00
ItemsInCart         0.00
CouponCode         25.75
ReferralSource      0.00
TotalPrice          0.00
dtype: float64

# Step 6: Handle Missing Values

In [12]:
num_cols=df.select_dtypes(include=np.number)

for col in num_cols:
    df[col]=df[col].fillna(df[col].median())

In [13]:
cat_cols=df.select_dtypes(include='object')

for col in cat_cols:
    df[col]=df[col].fillna(df[col].mode()[0])

# Step 7: Find Duplicate Records

In [14]:
duplicates=df.duplicated().sum()

print("Duplicates:",duplicates)

Duplicates: 0

# Step 8: Remove Duplicates

In [15]:
df=df.drop_duplicates()

print(df.shape)

(1200, 14)

# Step 9: Check Duplicate IDs

In [16]:
duplicate_ids = df["OrderID"].duplicated().sum()

print(duplicate_ids)

0

# Step 7: Check Data Types

In [17]:
print(df.dtypes)

OrderID                    object
Date               datetime64[ns]
CustomerID                 object
Product                    object
Quantity                    int64
UnitPrice                 float64
ShippingAddress            object
PaymentMethod              object
OrderStatus                object
TrackingNumber             object
ItemsInCart                 int64
CouponCode                 object
ReferralSource             object
TotalPrice                float64
dtype: object

In [18]:
df["Date"] = pd.to_datetime(df["Date"])

print(df["Date"].head())

0   2023-01-04
1   2024-08-23
2   2024-02-27
3   2023-10-15
4   2025-05-08
Name: Date, dtype: datetime64[ns]

# Step 8: Remove Extra Spaces (Text Cleaning)

In [19]:
text_columns = df.select_dtypes(include="object").columns

for col in text_columns:
    df[col] = df[col].str.strip()

print("Spaces Removed")

Spaces Removed

# Step 9: Standardize Text Format

In [27]:
df["Date"] = pd.to_datetime(df["Date"], errors="coerce", dayfirst=True)

In [20]:
df["Product"] = df["Product"].str.title()

df["OrderStatus"] = df["OrderStatus"].str.title()

In [21]:

print(df[["Product","OrderStatus"]].head())

   Product OrderStatus
0  Monitor     Shipped
1    Phone     Shipped
2   Tablet   Cancelled
3    Chair    Returned
4  Printer   Delivered

# Step 10: Verify No Duplicate Order IDs

In [22]:
duplicate_ids = df["OrderID"].duplicated().sum()

print("Duplicate Order IDs:", duplicate_ids)

Duplicate Order IDs: 0

# Step 11: Verify Date Format

In [23]:
print(df["Date"].dtype)

datetime64[ns]

In [28]:
print(df["Date"].head())
print(df["Date"].dtype)

0   2023-01-04
1   2024-08-23
2   2024-02-27
3   2023-10-15
4   2025-05-08
Name: Date, dtype: datetime64[ns]
datetime64[ns]

# Step 12: Save Cleaned Dataset

In [31]:
df["Date"] = pd.to_datetime(df["Date"]).dt.strftime("%d-%m-%Y")

In [32]:
df.to_excel("Cleaned_Dataset.xlsx",index=False)

print("Dataset Saved Successfully")

Dataset Saved Successfully

In [33]:
files.download("Cleaned_Dataset.xlsx")

# Step 13: Create Change Log (Important for Submission)

In [26]:
change_log = {

"Missing Values":"Filled CouponCode missing values",

"Duplicates":"Removed duplicate rows",

"Formatting":"Standardized date and text formats"

}

print(change_log)

{'Missing Values': 'Filled CouponCode missing values', 'Duplicates': 'Removed duplicate rows', 'Formatting': 'Standardized date and text formats'}